# Generated by Django 5.1 on 2024-09-10 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='project',
        ),
    ]
